import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Download, FileText, Table } from "lucide-react";
import { SearchResult } from "@/types/search";

interface ExportDataProps {
  searchResults: SearchResult[];
}

export const ExportData = ({ searchResults }: ExportDataProps) => {
  const exportToCSV = () => {
    if (searchResults.length === 0) return;

    const csvHeaders = [
      'Search Query',
      'Search Date',
      'Retailer',
      'Price',
      'Shipping',
      'Total Price',
      'Availability',
      'Rating',
      'Last Updated'
    ];

    const csvData = searchResults.flatMap(result =>
      result.prices.map(price => [
        result.searchQuery,
        result.timestamp.toISOString(),
        price.retailer,
        price.price.toFixed(2),
        (price.shipping || 0).toFixed(2),
        (price.price + (price.shipping || 0)).toFixed(2),
        price.availability,
        price.rating || 'N/A',
        price.lastUpdated.toISOString()
      ])
    );

    const csvContent = [csvHeaders, ...csvData]
      .map(row => row.map(field => `"${field}"`).join(','))
      .join('\n');

    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const link = document.createElement('a');
    link.href = URL.createObjectURL(blob);
    link.download = `price_comparison_${new Date().toISOString().split('T')[0]}.csv`;
    link.click();
  };

  const exportToJSON = () => {
    if (searchResults.length === 0) return;

    const jsonData = {
      exportDate: new Date().toISOString(),
      totalSearches: searchResults.length,
      searches: searchResults
    };

    const blob = new Blob([JSON.stringify(jsonData, null, 2)], { type: 'application/json' });
    const link = document.createElement('a');
    link.href = URL.createObjectURL(blob);
    link.download = `price_comparison_${new Date().toISOString().split('T')[0]}.json`;
    link.click();
  };

  const generateSummaryReport = () => {
    if (searchResults.length === 0) return;

    const totalSearches = searchResults.length;
    const totalProducts = searchResults.reduce((acc, result) => acc + result.prices.length, 0);
    const avgPricesPerSearch = (totalProducts / totalSearches).toFixed(1);
    
    const allPrices = searchResults.flatMap(result => result.prices);
    const uniqueRetailers = [...new Set(allPrices.map(price => price.retailer))];
    
    const bestDeals = searchResults.map(result => {
      const bestPrice = result.prices.reduce((best, current) => 
        (current.price + (current.shipping || 0)) < (best.price + (best.shipping || 0)) ? current : best
      );
      return {
        product: result.searchQuery,
        bestPrice: (bestPrice.price + (bestPrice.shipping || 0)).toFixed(2),
        retailer: bestPrice.retailer
      };
    });

    const reportContent = `
PRICE COMPARISON SUMMARY REPORT
Generated on: ${new Date().toLocaleString()}

OVERVIEW:
- Total searches performed: ${totalSearches}
- Total price points analyzed: ${totalProducts}
- Average retailers per search: ${avgPricesPerSearch}
- Unique retailers found: ${uniqueRetailers.length}

RETAILERS COVERED:
${uniqueRetailers.map(retailer => `- ${retailer}`).join('\n')}

BEST DEALS FOUND:
${bestDeals.map(deal => `- ${deal.product}: $${deal.bestPrice} at ${deal.retailer}`).join('\n')}

This report was generated by the Price Comparison Tool.
    `.trim();

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const link = document.createElement('a');
    link.href = URL.createObjectURL(blob);
    link.download = `price_comparison_report_${new Date().toISOString().split('T')[0]}.txt`;
    link.click();
  };

  if (searchResults.length === 0) {
    return (
      <Card>
        <CardContent className="p-8 text-center">
          <Download className="h-12 w-12 text-gray-400 mx-auto mb-4" />
          <h3 className="text-lg font-semibold text-gray-600 mb-2">No Data to Export</h3>
          <p className="text-gray-500">Perform some price comparisons first to export your data.</p>
        </CardContent>
      </Card>
    );
  }

  const totalSearches = searchResults.length;
  const totalPrices = searchResults.reduce((acc, result) => acc + result.prices.length, 0);

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Download className="h-5 w-5" />
            Export Your Data
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-6">
            <div className="text-center p-4 bg-blue-50 rounded-lg">
              <p className="text-2xl font-bold text-blue-600">{totalSearches}</p>
              <p className="text-sm text-gray-600">Total Searches</p>
            </div>
            <div className="text-center p-4 bg-green-50 rounded-lg">
              <p className="text-2xl font-bold text-green-600">{totalPrices}</p>
              <p className="text-sm text-gray-600">Price Points Analyzed</p>
            </div>
          </div>
          
          <p className="text-gray-600 mb-6">
            Export your price comparison data in various formats for further analysis or record keeping.
          </p>
        </CardContent>
      </Card>

      <div className="grid gap-4 md:grid-cols-3">
        <Card className="hover:shadow-md transition-shadow">
          <CardContent className="p-6 text-center">
            <Table className="h-12 w-12 text-blue-600 mx-auto mb-4" />
            <h3 className="font-semibold mb-2">CSV Export</h3>
            <p className="text-sm text-gray-600 mb-4">
              Spreadsheet-ready format for data analysis
            </p>
            <Button onClick={exportToCSV} className="w-full">
              <Download className="h-4 w-4 mr-2" />
              Export CSV
            </Button>
          </CardContent>
        </Card>

        <Card className="hover:shadow-md transition-shadow">
          <CardContent className="p-6 text-center">
            <FileText className="h-12 w-12 text-green-600 mx-auto mb-4" />
            <h3 className="font-semibold mb-2">JSON Export</h3>
            <p className="text-sm text-gray-600 mb-4">
              Structured data format for developers
            </p>
            <Button onClick={exportToJSON} variant="outline" className="w-full">
              <Download className="h-4 w-4 mr-2" />
              Export JSON
            </Button>
          </CardContent>
        </Card>

        <Card className="hover:shadow-md transition-shadow">
          <CardContent className="p-6 text-center">
            <FileText className="h-12 w-12 text-purple-600 mx-auto mb-4" />
            <h3 className="font-semibold mb-2">Summary Report</h3>
            <p className="text-sm text-gray-600 mb-4">
              Human-readable summary of your searches
            </p>
            <Button onClick={generateSummaryReport} variant="outline" className="w-full">
              <Download className="h-4 w-4 mr-2" />
              Generate Report
            </Button>
          </CardContent>
        </Card>
      </div>
    </div>
  );
};
